server:
  port: 8080

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# Configuração do Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      risk-service:
        registerHealthIndicator: true
        slidingWindowSize: 5          # Analisa as últimas 5 chamadas
        minimumNumberOfCalls: 3       # Precisa de pelo menos 3 para decidir
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s   # Fica aberto (falhando rápido) por 5s
        failureRateThreshold: 50      # Se 50% der erro, abre o bico
        eventConsumerBufferSize: 10
